/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hesong_smartbus_client_net_JniWrapper */

#ifndef _Included_com_hesong_smartbus_client_net_JniWrapper
#define _Included_com_hesong_smartbus_client_net_JniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hesong_smartbus_client_net_JniWrapper
 * Method:    Init
 * Signature: (B)I
 */
JNIEXPORT jint JNICALL Java_com_hesong_smartbus_client_net_JniWrapper_Init
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     com_hesong_smartbus_client_net_JniWrapper
 * Method:    Release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hesong_smartbus_client_net_JniWrapper_Release
  (JNIEnv *, jclass);

/*
 * Class:     com_hesong_smartbus_client_net_JniWrapper
 * Method:    CreateConnect
 * Signature: (BJLjava/lang/String;SLjava/lang/String;SLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hesong_smartbus_client_net_JniWrapper_CreateConnect
  (JNIEnv *, jclass, jbyte, jlong, jstring, jshort, jstring, jshort, jstring, jstring, jstring);

/*
 * Class:     com_hesong_smartbus_client_net_JniWrapper
 * Method:    SendText
 * Signature: (BBBIIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hesong_smartbus_client_net_JniWrapper_SendText
  (JNIEnv *, jclass, jbyte, jbyte, jbyte, jint, jint, jint, jstring);

/*
 * Class:     com_hesong_smartbus_client_net_JniWrapper
 * Method:    RemoteInvokeFlow
 * Signature: (BIILjava/lang/String;Ljava/lang/String;IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hesong_smartbus_client_net_JniWrapper_RemoteInvokeFlow
  (JNIEnv *, jclass, jbyte, jint, jint, jstring, jstring, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
